### ISSUE TITLE
Packaging Plan: Arch User Repository

### ISSUE THREAD

**Issue by kevr** [paulguy/crustygame#4]
I just wanted to create this issue here so we could possibly plan how we would package this to work as a system-installed program.

I do remember previously that there were some script files that one would specify to crustygame or so in order to launch the correct game. I'd like to try to make this out of the box in a sort of `crustris` launcher. I have not seen what you've done with the new age of crustygame, however; so I'm just leaving this here so that we can discuss things as needed.

I'll check out everything about how crustris works starting in a few hours from now.

**Comment by paulguy** [comment]
I know we've discussed this on IRC but just to leave a note here to keep track of things that need to be done.

Where things go needs to be determined.  Crustygame itself is just a standalone binary with no other files it depends on other than libraries that would be installed on the system.  Crustris requires its own set of files (main module, includes, graphics) stored somewhere in like /usr/share I guess, then it needs a space for saved games.  Crustygame saved games are always just single files named after the main crustygame program module.  Obviously these would go in the user's home directory.  I'm guessing we'd want to make this use XDG for where to put saved games.

As for launching it, I imagine a desktop file or script or something just placing the CWD in the base directory for crustygame/crustris (the examples directory in the repo), then running crustygame passing crustris.cvm would probably do.  Might want to maybe also have a few for different windowed resolutions?  as the default is 640x480, but can be passed a resolution on the command line for running in a window or indicated to just run in a borderless fullscreen window without changing display modes (toggleable at runtime).

There's a lot of details but it doesn't matter much.  It's just notes for considering what to do.

**Comment by paulguy** [comment]
XDG support is completed with 14a6e94fa8598e8e43f55dfd29674d5b64c97aa9.  That should be all the functionality necessary for now to make it packageable, unless something else comes up.  Will leave this open for now until everything is hammered out.

**Comment by kevr** [comment]
Very nice. Thank you, Paul! You made quick work of that.

**Comment by paulguy** [comment]
A bit late, this has been packaged and put up on AUR after this stuff has been worked out.
