### ISSUE TITLE
crustris Typo

### ISSUE THREAD

**Issue by kevr** [paulguy/crustygame#5]
Hello paulguy,

While playing `crustris`, I see a helpful description on the left side which tells the user which keys do what.

This is awesome. However, there is one slight issue: the `D` key is described as "Move Up," where the `D` key actually moves right.

Thanks for all of your hard work and awesome games!

**Comment by paulguy** [comment]
Fixed with 6c3829509f02334f921e3aba33e64aa0a09285ca.
